version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo "Installing deps"
      - echo $GEM_PATH
      - gem install bundler:2.0.1
      - bundle install --path src/vendor/bundle --deployment
      # this is a hack, becuase codebuild ruby runtime is 2.6 and lambda's is 2.5
      - mv src/vendor/bundle/ruby/2.6.0 src/vendor/bundle/ruby/2.5.0
  pre_build:
    commands:
      - echo "nothing to do on pre-build"
  build:
    commands:
      - echo "Nothing to do on build phase"
  post_build:
    commands:
      - echo "Running sam package on `date`"
      - echo "Dir contents `ls -alR`"
      - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yml
      - echo "build completed on `date`"

artifacts:
  type: zip
  files:
    - packaged.yml
  discard-paths: yes