version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "nothing to do on pre-build"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - packaged.yml
  discard-paths: yes